name: CI/CD for Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        docker ps -q --filter "publish=80" | xargs -r docker stop
        docker ps -aq --filter "publish=80" | xargs -r docker rm
        docker pull ashoknallam/ops-odyssey-flask:v1
        docker run -d -p 80:5000 --name ops-odyssey ashoknallam/ops-odyssey-flask:v1
      EOF
